name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make g++

    - name: Configure CMake
      run: |
        rm -rf ${{github.workspace}}/build
        mkdir ${{github.workspace}}/build
        cmake -B ${{github.workspace}}/build -S ${{github.workspace}}

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build
